version: '3.3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - rabbitmq
    environment:
      USE_PROXY_EDITOR: 'false'
      DB_FILE: './db.sqlite'
      RABBIT_HOST: 'rabbitmq'
      JWT_SECRET: WHATWHAT
      GOOGLE_PROFILE_API_URL: https://www.googleapis.com/oauth2/v1/userinfo
      GOOGLE_CLIENT_ID: 1031579332754-ql323h2k9ae4c0us047tt7m1mgb0n148.apps.googleusercontent.com
      GOOGLE_SECRET: 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
    ports:
      - "3000:3000"

  openai:
    image: zwisler/ada-openai:latest
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: "amqp://rabbitmq"
      OPENAI_API_KEY: ''

  whatsapp:
    image: zwisler/ada-whatsapp:latest
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: "amqp://rabbitmq"
