version: '3.3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - "5671:5672"
      - "15672:15672"

  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "3001:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: 'amqp://rabbitmq'
      USE_PROXY_EDITOR: 'false'
      DB_FILE: './db.sqlite'
      RABBIT_HOST: 'rabbitmq'
      AUTH_URL: 'http://auth.localhost/'
      JWKS_URL: 'http://auth:8080/.well-known/jwks.json'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)"
      - "traefik.http.routers.app.entrypoints=web"
    ports:
      - "3000:3000"

  ui:
    image: zwisler/ada-ui:latest
    ports:
      - "4200:80"
    environment:
      CORE_URL: "http://localhost"
      AUTH_URL: "http://auth.localhost/"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui.rule=Host(`ui.localhost`)"
      - "traefik.http.routers.ui.entrypoints=web"

  auth:
    image: zwisler/ada-auth:latest
    environment:
      BASE_URL: "http://auth.localhost/"
      ALLOWED_REDIRECTS: "http://ui.localhost/"
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.localhost`)"
      - "traefik.http.routers.auth.entrypoints=web"

  openai:
    image: zwisler/ada-openai:latest
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: "amqp://rabbitmq"
      OPENAI_API_KEY: ${OPEN_AI_KEY}

  whatsapp:
    image: zwisler/ada-whatsapp:latest
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: "amqp://rabbitmq"
